apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test237 
  janus-idp.io/tekton: test237
  backstage.io/kubernetes-id: test237
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test237
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  