apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test237
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test237 
  name: test237
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test237 
